# Generated by Django 2.2.3 on 2019-07-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profiles', '0002_auto_20190722_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='identicon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
