# Generated by Django 2.2.3 on 2019-07-19 10:52

import django.core.validators
from django.db import migrations, models
import my_universities.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuniversity',
            name='degree',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='myuniversity',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='myuniversity',
            name='grade',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='myuniversity',
            name='en_year',
            field=models.IntegerField(blank=True, default=my_universities.models.current_year, null=True, validators=[django.core.validators.MinValueValidator(1970), my_universities.models.max_value_current_year], verbose_name='en_year'),
        ),
        migrations.AlterField(
            model_name='myuniversity',
            name='st_year',
            field=models.IntegerField(blank=True, default=my_universities.models.current_year, null=True, validators=[django.core.validators.MinValueValidator(1970), my_universities.models.max_value_current_year], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='myuniversity',
            name='uni_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
